apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: provider-test-sonarqube
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: provider-test
    server: https://kubernetes.default.svc
  project: 2-services
  source:
    path: payload/2-services/namespace/provider-test/sonarqube
    repoURL: https://github.com/cloud-native-toolkit-test/provider-test-65z5gl
    targetRevision: main
    helm:
      releaseName: sonarqube
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences: []
